画面遷移図
wassupdee/RUNTEQ_portfolio pull request #2
Opened 2024-07-04 05:50 UTC by wassupdee

### READMEに記載した機能
- [x] ユーザー登録
- [x] ログイン
- [x] パスワード変更
- [x] メールアドレス変更

- [x] AIによるメッセージ提案（未ログインでも可能）
- [x] ワンクリックコピー（未ログインでも可能）
- [x] LINE転送

- [x] グループ一覧
- [x] グループ作成
- [x] グループ編集
- [x] グループ削除

- [x] 友人一覧
- [x] 友人詳細
- [x] 友人編集
- [x] 友人削除

- [x] 思い出アルバム作成
- [x] 思い出アルバム編集
- [x] 思い出アルバム作成
- [x] 画像アップロード
- [x] 画像削除
- [x] ノート作成
- [x] ノート編集

- [x] メモ作成
- [x] メモ編集
- [x] メモ保存

- [x] 通知設定
- [x] Googleカレンダー連携
- [x] マルチ検索

### 未ログインでも閲覧または利用できるページ
以下の項目は適切に未ログインでも閲覧または利用できる画面遷移になっているか？
- [x] AIによるメッセージ提案（未ログインでも可能）
- [x] ワンクリックコピー（未ログインでも可能）

### メールアドレス・パスワード変更確認項目
直接変更できるものではなく、一旦メールなどを介して専用のページで変更する画面遷移になっているか？
- [x] メールアドレス
- [x] パスワード

2024-07-04 10:01 UTC, tarakish requested changes
権限がなく確認ができませんでしたので権限周りの設定のご確認をお願いします！

![スクリーンショット 2024-07-04 19 00 27](https://github.com/wassupdee/RUNTEQ_portfolio/assets/71510236/fd1eab41-543c-46e8-b9d5-5e5275e9a3b1)

2024-07-04 23:55 UTC, wassupdee commented
申し訳ございませんでした。
ただいま、権限を変更しましたので、ご確認の程、どうぞよろしくお願いいたします。

[![Image from Gyazo](https://i.gyazo.com/50a0ebe29adfa1e0b4cf400f987b3191.png)](https://gyazo.com/50a0ebe29adfa1e0b4cf400f987b3191)

2024-07-05 01:53 UTC, tmtkzk0823 commented
概ね良さそうです！
LGTMです！

2024-07-05 03:53 UTC, wassupdee commented
ご確認、どうもありがとうございました！

2024-07-05 03:53 UTC, merged